### ISSUE TITLE
Unable to create part in Inventree using LCSC

### ISSUE THREAD

**Issue by StormTrooper** [sparkmicro/Ki-nTree#121]
I've installed the latest version of Inventree (0.11.0) and also installed the latest version of KI-nTree (0.6.6)

Have setup and tested the connection to inventree and also tested the connection to LCSC  and both work. 
I can retrieve the part info from LCSC but when I try and create the part in inventree it fails with:

Error occurred during API request - Ensure this field has no more than 100 characters

I have also setup a API key to Digikey and that works and the part is created. There only seem to be an issue with LCSC.

```
[MAIN]	Connecting to Inventree server
[TREE]	Successfully connected to InvenTree server (ENV=DEVELOPMENT)

--------------------

[MAIN]	Using LCSC cached data for C14877

[MAIN]	Creating part in Inventree
[INFO]	Category: "Integrated Circuits"
[INFO]	Subcategory: "MCU"
[INFO]	User Category: "Integrated Circuits"
[INFO]	User Subcategory: "MCU"
[INFO]	Warning: Parameter "Clock Frequency" not found in supplier data
[INFO]	Warning: Parameter "Speed" not found in supplier data
[INFO]	Warning: Parameter "Data Rate" not found in supplier data
[INFO]	Warning: Parameter "Frequency Range" not found in supplier data
[INFO]	Warning: Parameter "-3db Bandwidth" not found in supplier data
[INFO]	Warning: Parameter "Translator Type" not found in supplier data
[INFO]	Warning: Parameter "Technology" not found in supplier data
[INFO]	Warning: Parameter "Core Processor" not found in supplier data
[INFO]	Warning: Parameter "Type" not found in supplier data
[INFO]	Warning: Parameter "Sensor Type" not found in supplier data
[INFO]	Warning: Parameter "Program Memory Size" not found in supplier data
[INFO]	Warning: Parameter "Memory Size" not found in supplier data
[INFO]	Warning: Parameter "Channels per Circuit" not found in supplier data
[INFO]	Warning: Parameter "Package / Case" not found in supplier data
[INFO]	Warning: Parameter "Voltage - VCCA" not found in supplier data
[INFO]	Warning: Parameter "Voltage - VCCB" not found in supplier data
[INFO]	Warning: Parameter "Voltage - Supply" not found in supplier data
[INFO]	Warning: Parameter "Voltage - Supply (Vcc/Vdd)" not found in supplier data
[INFO]	Warning: Parameter "Voltage - Supply, Digital" not found in supplier data
[INFO]	Warning: Parameter "Voltage - Supply, Single (V+)" not found in supplier data
[INFO]	Warning: Parameter "Operating Temperature" not found in supplier data
Traceback (most recent call last):
  File "/home/greg/env-kintree/bin/kintree", line 8, in <module>
    sys.exit(main())
  File "/home/greg/env-kintree/lib/python3.10/site-packages/kintree/kintree_gui.py", line 1389, in main
    new_part, part_pk, part_data = inventree_interface.inventree_create(part_info=part_info,
  File "/home/greg/env-kintree/lib/python3.10/site-packages/kintree/database/inventree_interface.py", line 465, in inventree_create
    part_pk = inventree_api.create_part(category_id=category_select,
  File "/home/greg/env-kintree/lib/python3.10/site-packages/kintree/database/inventree_api.py", line 301, in create_part
    part = Part.create(inventree_api, {
  File "/home/greg/env-kintree/lib/python3.10/site-packages/inventree/base.py", line 144, in create
    response = api.post(cls.URL, data)
  File "/home/greg/env-kintree/lib/python3.10/site-packages/inventree/api.py", line 375, in post
    response = self.request(
  File "/home/greg/env-kintree/lib/python3.10/site-packages/inventree/api.py", line 327, in request
    raise requests.exceptions.HTTPError(detail)
requests.exceptions.HTTPError: {'detail': 'Error occurred during API request', 'url': 'http://192.168.1.87:8000/api/part/', 'method': 'POST', 'status_code': 400, 'body': '{"name":["Ensure this field has no more than 100 characters."]}', 'headers': {'AUTHORIZATION': 'Token **REMOVED**'}, 'params': {'format': 'json'}, 'data': {'name': '16KB -40℃~+85℃ 1.8V~5.5V AVR 2KB 16KB Yes 20MHz 10bit 23 TQFP-32(7x7)  Microcontroller Units (MCUs/MPUs/SOCs) ROHS', 'description': '16KB -40℃~+85℃ 1.8V~5.5V AVR 2KB 16KB Yes 20MHz 10bit 23 TQFP-32(7x7)  Microcontroller Units (MCUs/MPUs/SOCs) ROHS', 'category': 13, 'keywords': '16KB -40℃~+85℃ 1.8V~5.5V AVR 2KB 16KB Yes 20MHz 10bit 23 TQFP-32(7x7)  Microcontroller Units (MCUs/MPUs/SOCs) ROHS', 'revision': 'A', 'active': True, 'virtual': False, 'component': True, 'purchaseable': True}}


```

**Comment by StormTrooper** [comment]
After some more digging it looks like this is due to the record size on name which is set to 100 chars in Inventree.  
Closing as not a Ki-nTree issue
