### ISSUE TITLE
LCSC Part search for a "not found" part number throws "Future exception was never retrieved" MacOS

### ISSUE THREAD

**Issue by plocher** [sparkmicro/Ki-nTree#261]
[MAIN]	LCSC search for C100043
Future exception was never retrieved
future: <Future finished exception=TypeError("'NoneType' object is not iterable")>
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.10/3.10.15/Frameworks/Python.framework/Versions/3.10/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/homebrew/lib/python3.10/site-packages/flet_core/page.py", line 941, in wrapper
    handler(*args)
  File "/opt/homebrew/lib/python3.10/site-packages/kintree/gui/views/main.py", line 444, in perform_pn_search
    self.run_search(e)
  File "/opt/homebrew/lib/python3.10/site-packages/kintree/gui/views/main.py", line 330, in run_search
    part_supplier_info = inventree_interface.supplier_search(
  File "/opt/homebrew/lib/python3.10/site-packages/kintree/database/inventree_interface.py", line 493, in supplier_search
    part_info = lcsc_api.fetch_part_info(part_number)
  File "/opt/homebrew/lib/python3.10/site-packages/kintree/search/lcsc_api.py", line 84, in fetch_part_info
    for key in part:
TypeError: 'NoneType' object is not iterable

**Comment by T0jan** [comment]
small bug. probably only in the following line `None` needs to be changed to an empty list/tuple/dict:

https://github.com/sparkmicro/Ki-nTree/blob/f49f276efab644e3b85605e69c1ec9266c187350/kintree/search/lcsc_api.py#L72
